"""init tables

Revision ID: 8047c005fa43
Revises: 
Create Date: 2026-03-28 16:10:33.757589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8047c005fa43'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('currencies', sa.String(length=200), nullable=False),
    sa.Column('pairs', sa.String(length=500), nullable=False),
    sa.Column('sides', sa.String(length=100), nullable=False),
    sa.Column('net_profit_pct', sa.Float(), nullable=False),
    sa.Column('net_profit_usdt', sa.Float(), nullable=False),
    sa.Column('initial_amount', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('total_fees', sa.Float(), nullable=False),
    sa.Column('total_slippage', sa.Float(), nullable=False),
    sa.Column('raw_rate_product', sa.Float(), nullable=False),
    sa.Column('legs_json', sa.Text(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('total_cycles_detected', sa.Integer(), nullable=False),
    sa.Column('total_trades_executed', sa.Integer(), nullable=False),
    sa.Column('total_profit_usdt', sa.Float(), nullable=False),
    sa.Column('avg_profit_pct', sa.Float(), nullable=False),
    sa.Column('best_profit_pct', sa.Float(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trade_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('currencies', sa.String(length=200), nullable=False),
    sa.Column('pairs', sa.String(length=500), nullable=False),
    sa.Column('sides', sa.String(length=100), nullable=False),
    sa.Column('initial_amount', sa.Float(), nullable=False),
    sa.Column('final_amount', sa.Float(), nullable=False),
    sa.Column('profit_usdt', sa.Float(), nullable=False),
    sa.Column('profit_pct', sa.Float(), nullable=False),
    sa.Column('total_fees', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('executed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trade_history')
    op.drop_table('daily_stats')
    op.drop_table('cycle_snapshots')
    # ### end Alembic commands ###
