"""add spot_futures_history table

Revision ID: 828ed5607b4b
Revises: 8047c005fa43
Create Date: 2026-03-29 13:55:25.829816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '828ed5607b4b'
down_revision: Union[str, Sequence[str], None] = '8047c005fa43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spot_futures_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('spot_price', sa.Float(), nullable=False),
    sa.Column('futures_price', sa.Float(), nullable=False),
    sa.Column('premium_pct', sa.Float(), nullable=False),
    sa.Column('net_profit_pct', sa.Float(), nullable=False),
    sa.Column('direction', sa.String(length=30), nullable=False),
    sa.Column('funding_rate', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spot_futures_history')
    # ### end Alembic commands ###
